syntax = "proto3";

message ProjectProto {
  repeated GameNodeProto nodes = 1;
  repeated GameTransitionProto transitions = 2;
  repeated StructProto structs = 3;
}

message GameTransitionProto {
  string id = 1;
  string text = 2;
  string from = 3;
  string to = 4;
  int32 weight = 5;
  string jsCondition = 6;
  string jsAction = 7;
  repeated GenerateImageMetadataProto generatedImages = 8;
  string naturalLanguageCondition = 9;
  string naturalLanguageAction = 10;
}

message GameNodeProto {
  string id = 1;
  string text = 2;
  string label = 3;
  int64 x = 4;
  int64 y = 5;
  bool isStart = 6;
  string jsAction = 7;
  string imagePath = 8;
  repeated GenerateImageMetadataProto generatedImages = 9;
  string speaker = 11;
  string naturalLanguageAction = 12;
  string gotoLabel = 13;
}

message StructProto {
  string id = 1;
  string name = 2;
  repeated VariableProto variables = 3;
}

message VariableProto {
  oneof type {
    NumberVariableProto numberVariable = 1;
    NamedVariableProto namedVariable = 2;
  }
}

message NumberVariableProto {
  string id = 1;
  string name = 2;
  string initialValue = 3;
  string value = 4;
  string description = 5;
}

message NamedVariableProto {
  string id = 1;
  string name = 2;
  string typeId = 3;
  string initialValue = 4;
  string value = 5;
  string description = 6;
}

message GenerateImageMetadataProto {
  string id = 1;
  string style = 2;
  string description = 3;
  string llmGeneratedPrompt = 4;
}